version: "3.9"
services:
  appserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=Matomi1.
      - MYSQL_USER=matomi
      - MYSQL_DATABASE=stack_overflow
      - JWT_SECRET='stack_overflow_api'
      - JWT_EXPIRES_IN=1